### ISSUE TITLE
Category listing

### ISSUE THREAD

**Issue by yleaxeman** [folkehelseinstituttet/Fhi.Frontend.Demo#30]
Make each category collapsable using `<details><summary>`

![image](https://user-images.githubusercontent.com/8872303/159240436-61924182-b057-4823-9a53-a2b4d47ebf5e.png)

**Comment by proand** [comment]
It's the menu categories you'r talking about here, right?

**Comment by yleaxeman** [comment]
Yes:
![image](https://user-images.githubusercontent.com/8872303/134492384-676fe57a-3f39-423e-870b-d83bfcbffb63.png)

**Comment by proand** [comment]
@yleaxeman I'm closing this, since menu has changed since this issue was created
