### ISSUE TITLE
Language: norwegian -> english

### ISSUE THREAD

**Issue by yleaxeman** [folkehelseinstituttet/Fhi.Frontend.Demo#47]
The naming convention should be english. There are some directories that has been named in norwegian, these should all be translated.

Also look for other norwegian named elements, like variables etc.

Should the example texts and component naming be in norwegian or english?

**Comment by yleaxeman** [comment]
@proand - Will it have any inflictions on other libraries if we were to rename all files and folders that currently are named in norwegian?

**Comment by proand** [comment]
@yleaxeman I'm not 100% shure... we'll discuss this, and some other changes to file/folders later today.

**Comment by proand** [comment]
_Should the example texts and component naming be in norwegian or english?_
Yes, I think so!

**Comment by yleaxeman** [comment]
> _Should the example texts and component naming be in norwegian or english?_ @yleaxeman Yes, I think so!
@proand - Read the question one more time :-)

**Comment by proand** [comment]
> Should the example texts and component naming be in norwegian or english? @yleaxeman Yes, I think so!
> @proand - Read the question one more time :-)

@yleaxeman Ups! 😂 Correct answer is *english*!
