### ISSUE TITLE
Remove or change info text in fhi-angular-highcharts.component.html

### ISSUE THREAD

**Issue by VillereV** [folkehelseinstituttet/Fhi.Frontend.Demo#544]
**fhi-angular-highcharts.component.html**
`<em>Foreløpig ikke mulig å se at en diagramtype er disabled... det kommer en løsning på det ASAP!</em>`

This  information is useful for developers, but may be confusing for end users.

Solutions:

1. Remove/hide the text or
2. Make the text 'user friendly' or
3. Fix the issue

**Comment by proand** [comment]
BTW: It's the proposed solution 2. we are implementing: a "user friendly" text.
