### ISSUE TITLE
Datepicker: Formatting help for date input

### ISSUE THREAD

**Issue by cathral** [folkehelseinstituttet/Fhi.Frontend.Demo#558]
1. Input mask: If I have written the correct date, the "." will appear and I can continue with the month
2. Character type and value restriction: I don't want to be allowed to input illegal letters or numbers

Consider: For Date and time -> validation for both fields in one message. Maybe there is not so many thing that can go wrong if we restrict the user input?

<img width="573" alt="image" src="https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/assets/622109/6ca1d3a7-14df-4d57-9f4e-537e9098b33e">

**Comment by proand** [comment]
Dette kommer i det nye designsystemet.

**Comment by trybern** [comment]
Har notert dette i saken for tekstfelt i det nye systemet, så lukker saken som "ikke planlagt" i dette repo-et, for å holde ting ryddig.
