### ISSUE TITLE
Tree View Selection lost it's branch active state

### ISSUE THREAD

**Issue by yleaxeman** [folkehelseinstituttet/Fhi.Frontend.Demo#570]
While fixing #563, we lost the state to notify if children of a node has been selected

<img width="276" alt="image" src="https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/assets/8872303/7653483a-f606-482a-a9eb-09e70e55b845">

**Should be:**

<img width="279" alt="image" src="https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/assets/8872303/f12170e4-6a63-4955-86aa-4226e38457bf">

**Comment by yleaxeman** [comment]
This is handled in assistance by Team D

**Comment by bittakv** [comment]
I have a suggested soulution, PR will  be submitted soon, just have to go through the solution with @proand first
