### ISSUE TITLE
FhiTreeViewSelectionComponent: Unselected children of selected parents are expanded when the "expandCheckedItems" is set in updateDecendantState

### ISSUE THREAD

**Issue by bittakv** [folkehelseinstituttet/Fhi.Frontend.Demo#578]
Noden "Komponenter" er sjekket av, og barna til "Komponenter" er ekspandert:
![image](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/assets/99685938/814df9ff-960d-465c-aaea-4c867b7df621)

Det skal se slik ut, ("Komponenter" skal ikke være ekspandert):
![image](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/assets/99685938/4e400932-299c-444e-a9ca-29b0746b3fdc)

Items input:
```json:
Input items:
[
      {
        name: 'For utviklere',
        children: [
          {
            name: 'Visuell identitet',
          },
          {
            name: 'Komponenter',
            isChecked: true,  // <--------------- Checked parent-node node
            children: [
              {
                name: 'Accordions',
              },
              {
                name: 'Advanced select',
              },
              {
                name: 'Alerts',
              },
            ],
          },
          {
            name: 'Layout og sidemaler',
          },
        ],
      },
      {
        name: 'For designere',
        id: 'for-designere',
      },
      {
        name: 'Github',
        children: [
          {
            name: 'Fhi.Frontend.Style',
          },
        ],
      },
    ];
```

**Comment by dafn** [comment]
I accidentally posted this on the PR, but it belongs here:

Could you give me steps to reproduce the bug?

**Comment by bittakv** [comment]
The items passed to the component must have one or more items that has children, and the item must be checked. (As the item with name "Komponenter" in the input listed in the description.
