### ISSUE TITLE
FHI Angular Highcharts: enable SVG export

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Demo#618]
**Description**

The final solution for export is not decided upon, but in the meantime it would be nice to have an simplified solution that handles some use cases, e.g. just downloading an SVG as is.

**Acceptance Criteria**

Given:

1. The scope for a first iteration of the export functionality is agreed upon
2. Design for export is ready

Then:

1. Go to https://dev-designsystem.fhi.no/developer/components/highcharts#highcharts-all-inclusive
2. Check that there is an export controller
3. Click export SVG, PNG, etc.
4. Check that an SVG is downloaded to your pc

**Comment by proand** [comment]
@stalehaugenes Added new issue as discussed 🙂

**Comment by dafn** [comment]
is this issue connected to this PR?
https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/pull/627#pullrequestreview-2196001514
