### ISSUE TITLE
FHI Angular Highcharts: add reasons why chart or map can't be rendered in the warning messages

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Demo#625]
### Description

An end user of _FHI Angular Highcharts_ should be able to understand why a certain diagram type can't be rendered. Today the user only gets a very generic warning message.

### Acceptance Criteria

Given:

1. The logic behind the triggering of different messages is agreed upon
2. New messages are ready

Then:

1. Go to https://dev-designsystem.fhi.no/developer/components/highcharts#highcharts-all-inclusive
2. _...to be continued_

### Additional information

Here is an example of a dataset that shows the generic warning out in the wild:
https://statistikk.fhi.no/lmr/TNZLPRRR3Nsm1c7dvyi2gQ?MEASURE_TYPE=AntallBrukere&Atc_Verdi=L,M,N,P,R,S,V&Kjonn_Verdi=TOTALT&Aldersgruppe_Verdi=TOTALT&Utlevering_Ar=2004&DIAGRAM_TYPE=line

**Comment by proand** [comment]
@cathral Vi får se mer på denne når du kommer tilbake fra ferie 🙂 

FYI @bittakv

**Comment by proand** [comment]
There is code ready in this [branch](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/tree/enhancement/highcharts-improve-warning-msg--TMP) so that I, @cathral and @bittakv can take a look, and finish the Acceptance Criteria together. Until then, this Issue is blocked.

**Comment by proand** [comment]
Talked to Cathrine yesterday, and we have a plan ;)

**Comment by proand** [comment]
@cathral Here is the image as mentioned yesterday:



![Image](https://github.com/user-attachments/assets/bcf1cb46-e327-4054-a5eb-480fbb07ad4d)

**Comment by cathral** [comment]
<img width="845" alt="image" src="https://github.com/user-attachments/assets/db0de78b-b39f-4afe-a6c0-30ba49319a57">

**Comment by cathral** [comment]
Vi dropper melding for linjediagram

**Comment by cathral** [comment]
Bilde 2: Tekst som går på måleenhet

**Comment by proand** [comment]
Jeg og @cathral har landet på et kompromiss som løsnining på dette issuet: vi beholder dagens melding, og logger de mer komplekse meldingene til konsoll, slik at fag har tilgang til dem ved behov.

I tillegg:

- dropper vi, som nevnt, melding for linjediagram (bilde 3)
- og oppretter et nytt issue ang. det å vise prikkede data med flere serier som linje (se figur tre kommentarer opp)
