### ISSUE TITLE
Ikonbestilling: "lock" 

### ISSUE THREAD

**Issue by cathral** [folkehelseinstituttet/Fhi.Frontend.Demo#633]
Vi trenger denne for å vise at et element ikke kan redigeres:
https://icons.getbootstrap.com/icons/lock/

**Comment by proand** [comment]
Lukker denne da den hører til et annet repo. Har opprettet et nytt issue for deg @cathral https://github.com/folkehelseinstituttet/Fhi.Frontend.Style/issues/392

**Comment by cathral** [comment]
> Lukker denne da den hører til et annet repo. Har opprettet et nytt issue for deg @cathral [folkehelseinstituttet/Fhi.Frontend.Style#392](https://github.com/folkehelseinstituttet/Fhi.Frontend.Style/issues/392)

Takk! Nå ser det ut som vi også utsetter oppgaven. Jeg noterer det i den nye issuen.
