### ISSUE TITLE
FHI Angular Highcharts: Støtte for et ekstra tekstelement/ beskrivelse under overskift

### ISSUE THREAD

**Issue by cathral** [folkehelseinstituttet/Fhi.Frontend.Demo#649]
### Description

FHI Statistikk trenger støtte for en utdypende tekst under overskriften.

<img width="633" alt="image" src="https://github.com/user-attachments/assets/24826d2e-8978-41c2-be20-fef6d1d4d580">

**Comment by proand** [comment]
@dafn Jeg droppet å legge inn beskrivelse i demo-app-en, ser sånn ut:
![Image](https://github.com/user-attachments/assets/222cc1ae-ac6b-4b23-83a0-64728cd79ffd)
