### ISSUE TITLE
FHI Angular Highcharts: diagramtype navigation in full screen view fails if diagram type is disabled

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Demo#650]
### Description

When I try to show an disabled diagram type in full screen view no waring message is shown, and it is not possible to navigation to other diagram types.

### What was the expected result?

Should see waring message, and it should be possible to navigation to other diagram types.

### Steps to reproduce

1. Go to https://dev-designsystem.fhi.no/developer/components/highcharts#highcharts-all-inclusive
2. Click on the full screen button
3. Try to show map, and verify that nothing happens
4. Try to go back to column again, and verify that nothing happens

### Additional information

My proposed solution is to remove the diagram type navigation in full screen view, since to fix the bug is a bit cumbersome, and I don't think the navigation adds that much value in the full screen view.

**Comment by proand** [comment]
@trybern @cathral What do you think about my proposed solution?

**Comment by cathral** [comment]
Perfek/ct!
