### ISSUE TITLE
FHI Angular Highcharts: Heisann, kan det ha skjedd noe med kart i den nye releasen? (4.4.0)

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Demo#685]
### Description

![image](https://github.com/user-attachments/assets/095c6fc1-e08c-4faf-9d61-47129ef4d7e1)

### What was the expected result?

Skulle helst ikke hatt noe kart-knapp i det hele tatt

### Steps to reproduce

Ikke legg til  `items.mapTypes`

### Additional information

Legger en til:
![image](https://github.com/user-attachments/assets/fd54dd0a-751e-44ea-bb29-3f0427826d22)
...så forsvinner knappen, men i forrige release ble den vist dersom jeg ikke la til  `mapTypes` i `items`

**Comment by proand** [comment]
FYI @stalehaugenes

**Comment by proand** [comment]
@bittakv @stalehaugenes 

Bare sånn for å være på den sikre siden:

Dette gir en meny med alle diagramtyper som finnes tilgjenglig i komponenten pr. i dag

```ts
controls: {
  navigation: {
    show: true,
  },
},
```

Dette gir en meny med kun tabell

```ts
controls: {
  navigation: {
    items: {},
    show: true,
  },
},
```

Dette gir en meny tabell, pluss det som er definert, i den rekkefølgend de ligger i array-ene

```ts
controls: {
  navigation: {
    items: {
      chartTypes: ['bar', 'column', 'line', 'pie'],
      mapTypes: ['mapFylker2023'],
    },
    show: true,
  },
},
```

...er det som forventet og OK?

**Comment by bittakv** [comment]
LGTM :-)
