### ISSUE TITLE
FHI Angular Highcharts: Tilleggstekst ("disclaimer") i fotnote er vanskelig å lese

### ISSUE THREAD

**Issue by cathral** [folkehelseinstituttet/Fhi.Frontend.Demo#738]
### Description

![image](https://github.com/user-attachments/assets/90a4ce90-1c27-4545-8e3a-dc103efbba7f)

- Øk fontstørrelse og fjerne italic styling

### Acceptance Criteria

Fontstørrelse og stil er lik i admin og publikum i FHI statistikk -> [se Figma](https://www.figma.com/design/nHQ4tTswUxMaOvEahpxz18/FHI-Statistikk-Admin-og-Public?node-id=16701-97449&t=yHAWAmAmvlwRZkj4-1)

### Additional information

[Lenke til US i FHI Statistikk -> ](https://fhi.visualstudio.com/Team%20D/_workitems/edit/94909)

**Comment by proand** [comment]
Denne utgår, problemstillinger knyttet til "footer" må sees på under ett.
