### ISSUE TITLE
"fhi-tree-view-navigation" is not able to use in standalone components

### ISSUE THREAD

**Issue by yne-bv** [folkehelseinstituttet/Fhi.Frontend.Demo#742]
### Description

I have a component that is standalone and want to use the `fhi-tree-view-navigation`-component.
The `fhi-tree-view-navigation` is not standalone, and therefore can not be used.

**Comment by proand** [comment]
@yne-bv FYI: Issue is closed since #747 is merged to `dev`, but package isn't released yet.
